Desktop version
MargaretTechworld/Portfolio pull request #5
Opened 2023-06-09 10:56 UTC by MargaretTechworld

The Followin were added to this repository:
- Added Deskto version
- Styled Desktop Version
- Added a Customized Microverse Read Me Template.

Thank you for your Review.

2023-06-09 11:23 UTC, Efiamotu-1 requested changes
Hi @MargaretTechworld , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 11:23 UTC, Efiamotu-1 commented on README.md
- [ ] I noticed that you have not provided your actual handles for your `LinkedIn, Github & Twitter` Accounts because when clicked these applications only open but they do not open your personal account. Please kindly fix this by providing the actual accounts so that the link is correct when clicked :+1: :sparkles:

2023-06-09 11:23 UTC, Efiamotu-1 commented on index.html
- [ ] The top section of your portfolio application does not match completely the figma template with regards to the alignment of its contents and i have pointed them out to you with the red lines as shown in the figma image below. please kindly work on the alignment and spacing as shown on figma :+1: 
- figma design
![ed](https://github.com/MargaretTechworld/Portfolio/assets/89055502/f53c8776-cad3-4110-a673-100eecde5350)
- your design
![eds](https://github.com/MargaretTechworld/Portfolio/assets/89055502/37caa61d-95fd-42a4-9a32-ebc57bd5860d)

2023-06-09 11:23 UTC, Efiamotu-1 commented on index.html
- [ ] The cards as shown from the figma image below is centered in the middle of the viewport for desktop version please can you do this. it is important that your design matches closely the provided figma template because this shows your attention to details as a front end developer and it is a good skill to have :+1: 
- [ ] Also take note of the spacing between the image and the contents of each card. please ensure it reflects on each card.
- figma design
![eds](https://github.com/MargaretTechworld/Portfolio/assets/89055502/98bcc4ec-112c-4f71-947f-a80418a64962)
- your design
![ed-s](https://github.com/MargaretTechworld/Portfolio/assets/89055502/420ddb0a-4612-4c25-a210-a2bb1ffb8171)

2023-06-09 11:23 UTC, Efiamotu-1 commented on index.html
- [ ] The button for this card is currently showing the way it should show when it is hovered, its design is currently different from the other button. please kindly adjust the design so it shows like others when it is not being hovered on :+1: 
- your design
![cds](https://github.com/MargaretTechworld/Portfolio/assets/89055502/46fbb880-6471-42da-bafd-cbaff8b63440)

2023-06-09 11:23 UTC, Efiamotu-1 commented on index.html
- [ ] Please kindly work on the spacing as depicted by the red lines in the images below. :+1: 
- figma design
![tsp](https://github.com/MargaretTechworld/Portfolio/assets/89055502/f0eba9e4-7ed6-48d0-8190-228920c9439f)
- your design
![tssp](https://github.com/MargaretTechworld/Portfolio/assets/89055502/483d82ea-bd2a-43ee-bb5f-b3ad7e85f940)

2023-06-09 11:23 UTC, Efiamotu-1 commented on index.html
- [ ] As shown in the figma image below the contents of your contact me should be centered in the middle on the desktop view. please kindly work on centering the contents so your design matches the provided figma design :+1: :sparkles:  
- figma design
![ccm](https://github.com/MargaretTechworld/Portfolio/assets/89055502/0f46750f-8452-430d-954c-22b39ab45e19)

2023-06-10 12:23 UTC, usorfaitheloho requested changes
> Hi @MargaretTechworld ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Fixed some errors suggested  by the previous reviewer ✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 12:23 UTC, usorfaitheloho commented on index.html
while you made a great effort in implementing the changes suggested by the previous reviewer, you should ensure that while making the changes you dont tamper with the other parts of the contacty form. In your current contact form section, the background images have been distorted. kindly fix the background image in this section so it looks close to the design available and also increase the width of the form boxes so your design looks closely similar to the figma design given

Your design :

![image](https://github.com/MargaretTechworld/Portfolio/assets/20537712/f08789cd-f1cb-47b9-a861-d77b92a18685)

figma design :

![image](https://github.com/MargaretTechworld/Portfolio/assets/20537712/beeff971-7016-4221-b191-cbfd85032a39)

2023-06-10 13:26 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @MargaretTechworld,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-10 13:32 UTC, merged